import type { Metadata } from "next";
import "../globals.css";
export const metadata: Metadata = {
  title: "premium",
  description: "Generated by create next app",
};

export default function PremiumLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main>{children}</main>;
}
