import type { Metadata } from "next";
import "../../globals.css";
import { VectorFilterContextProvider } from "@/context/useVectorFilter";
export const metadata: Metadata = {
  title: "vectors",
  description: "Generated by create next app",
};

export default function VectorsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <VectorFilterContextProvider>{children}</VectorFilterContextProvider>
    </div>
  );
}
