import type { Metadata } from "next";
import "../globals.css";
import { TabContextProvider } from "@/context/useTab";
import { VectorFilterContextProvider } from "@/context/useVectorFilter";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <TabContextProvider><VectorFilterContextProvider>{children}</VectorFilterContextProvider></TabContextProvider>
    </main>
  );
}
