import type { Metadata } from "next";
import "../globals.css";
import { TabContextProvider } from "@/context/useTab";
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <TabContextProvider>
        {children}
      </TabContextProvider>
    </main>
  );
}
